Updates metadata. Makes check if station is in metadata
metno/pyaro-readers pull request #50
Opened 2024-09-13 09:22 UTC by dulte

Small changes to eeareader

2024-09-13 10:13 UTC, dulte commented
I've added the possibility to change units with a factor. Factor is added to data.toml. Might want a separate file for these factors

2024-09-13 10:13 UTC, dulte commented
I'm not sure with the files fail due to not finding data.toml. Will have a look next week

2024-09-13 10:14 UTC, heikoklein requested changes
Tests not working (still draft)? Very strange choice of variable/file-names.

2024-09-13 10:14 UTC, heikoklein commented on src/pyaro_readers/eeareader/EEATimeseriesReader.py
> +        self.datafile = self._read_data()
both `datafile` and `_read_data` and `data.toml` are very confusing here. It is everything but `data`=measurement of e.g. 17.35µg/m³, please find a better name. `cfg` or `setup`? And definitely don't call something for `file` which is neither a filename or filehandle.

2024-09-13 10:26 UTC, dulte commented
@heikoklein . Yes, right before you answered I changed it to a draft. The tests fail because they can't find data.toml, and I'm not entirely sure why... going to look at it over the weekend.

I've added a simple unit conversion field as well in data.toml. It seems to work, but I have to add some tests for that as well before the pr is ready for review

2024-09-15 21:32 UTC, dulte commented
Note to self: remove unit change from data.toml, and add it as a possible argument to the reader instead

2024-09-16 14:08 UTC, dulte commented
@heikoklein. Fixed some problems, and made some new ones. But it is now ready for review

2024-09-16 20:35 UTC, heikoklein approved these changes
Looks good, except for linting. You should really fix your black setup.

2024-09-23 08:19 UTC, merged